const rewards = [
  {
    id: 1,
    pic: "http://ddragon.leagueoflegends.com/cdn/12.22.1/img/item/1038.png",
    magicBuff: 5,
    physBuff: 5,
  },
  {
    id: 2,
    pic: "http://ddragon.leagueoflegends.com/cdn/12.22.1/img/item/1057.png",
    magicBuff: 5,
    defenseBuff: 5,
  },
  {
    id: 3,
    pic: "http://ddragon.leagueoflegends.com/cdn/12.22.1/img/item/3001.png",
    magicBuff: 5,
    poisonBuff: 3,
  },
  {
    id: 4,
    pic: "http://ddragon.leagueoflegends.com/cdn/12.22.1/img/item/2003.png",
    magicBuff: 5,
    healBuff: 5,
  },
  {
    id: 5,
    pic: "http://ddragon.leagueoflegends.com/cdn/12.22.1/img/item/3003.png",
    magicBuff: 5,
    startDistrib: 1,
  },
  {
    id: 6,
    pic: "http://ddragon.leagueoflegends.com/cdn/12.22.1/img/item/1026.png",
    magicBuff: 5,
    currentLife: 20,
    maxLife: 20,
  },
  {
    id: 7,
    pic: "http://ddragon.leagueoflegends.com/cdn/12.22.1/img/item/1031.png",
    physBuff: 5,
    defenseBuff: 5,
  },
  {
    id: 8,
    pic: "http://ddragon.leagueoflegends.com/cdn/12.22.1/img/item/3011.png",
    physBuff: 5,
    poisonBuff: 3,
  },
  {
    id: 9,
    pic: "http://ddragon.leagueoflegends.com/cdn/12.22.1/img/item/1053.png",
    physBuff: 5,
    healBuff: 5,
  },
  {
    id: 10,
    pic: "http://ddragon.leagueoflegends.com/cdn/12.22.1/img/item/3004.png",
    physBuff: 5,
    startDistrib: 1,
  },
  {
    id: 11,
    pic: "http://ddragon.leagueoflegends.com/cdn/12.22.1/img/item/3072.png",
    physBuff: 5,
    currentLife: 20,
    maxLife: 20,
  },
  {
    id: 12,
    pic: "http://ddragon.leagueoflegends.com/cdn/12.22.1/img/item/3068.png",
    defenseBuff: 5,
    poisonBuff: 3,
  },
  {
    id: 13,
    pic: "http://ddragon.leagueoflegends.com/cdn/12.22.1/img/item/3053.png",
    defenseBuff: 5,
    healBuff: 5,
  },
  {
    id: 14,
    pic: "http://ddragon.leagueoflegends.com/cdn/12.22.1/img/item/2038.png",
    defenseBuff: 5,
    startDistrib: 1,
  },
  {
    id: 15,
    pic: "http://ddragon.leagueoflegends.com/cdn/12.22.1/img/item/2051.png",
    defenseBuff: 5,
    currentLife: 20,
    maxLife: 20,
  },
  {
    id: 16,
    pic: "http://ddragon.leagueoflegends.com/cdn/12.22.1/img/item/4632.png",
    poisonBuff: 3,
    healBuff: 5,
  },
  {
    id: 17,
    pic: "http://ddragon.leagueoflegends.com/cdn/12.22.1/img/item/4635.png",
    poisonBuff: 3,
    startDistrib: 1,
  },
  {
    id: 18,
    pic: "http://ddragon.leagueoflegends.com/cdn/12.22.1/img/item/2033.png",
    poisonBuff: 3,
    currentLife: 20,
    maxLife: 20,
  },
  {
    id: 19,
    pic: "http://ddragon.leagueoflegends.com/cdn/12.22.1/img/item/3041.png",
    healBuff: 5,
    startDistrib: 1,
  },
  {
    id: 20,
    pic: "http://ddragon.leagueoflegends.com/cdn/12.22.1/img/item/1001.png",
    healBuff: 5,
    currentLife: 20,
    maxLife: 20,
  },
  {
    id: 21,
    pic: "http://ddragon.leagueoflegends.com/cdn/12.22.1/img/item/2419.png",
    startDistrib: 1,
    currentLife: 20,
    maxLife: 20,
  },
];

export default rewards;
